ALTER TABLE hopes.medicines ADD COLUMN med_content VARCHAR(150);
ALTER TABLE hopes.medicines ADD COLUMN med_authorization_date DATE;
ALTER TABLE hopes.medicines ADD COLUMN med_authorized BOOLEAN DEFAULT FALSE NOT NULL;
ALTER TABLE hopes.medicines ADD COLUMN med_end_date_authorization DATE;
ALTER TABLE hopes.medicines ADD COLUMN med_commercialization_date DATE;
ALTER TABLE hopes.medicines ADD COLUMN med_end_date_commercialization DATE;
ALTER TABLE hopes.medicines ADD COLUMN med_via_administration VARCHAR(150);
ALTER TABLE hopes.medicines ADD COLUMN med_brand VARCHAR(50);
ALTER TABLE hopes.medicines ADD COLUMN med_units INT;
ALTER TABLE hopes.medicines ADD COLUMN med_pvl decimal(13,2);
ALTER TABLE hopes.medicines ADD COLUMN med_pvl_unitary decimal(13,2);
ALTER TABLE hopes.medicines ADD COLUMN med_pvp decimal(13,2);
ALTER TABLE hopes.medicines ADD COLUMN med_pathology VARCHAR(150);
ALTER TABLE hopes.medicines ADD COLUMN med_family VARCHAR(150);
ALTER TABLE hopes.medicines ADD COLUMN med_subfamily VARCHAR(150);