---
plexus:
  hopes:
    email:
      template:
        default-sender: "no-reply@hopes.com"
        default-subject: "Reset your password"
        default-text: "Hopes password reset"
        reset-password-url: "/user/reset_password?token="

# Server settings
server:
  port: 8080
  servlet:
    context-path: "/v1"

spring:
  profiles:
    active: @spring.profiles.active@
  jpa:
    # Hibernate
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
        default_schema: "hopes"
        #enable_lazy_load_no_trans: true
    open-in-view: false
    show-sql: false
  # Thymeleaf
  thymeleaf:
    cache: false
    enabled: true
    prefix: "classpath:/templates/"
    suffix: ".html"
  # Liquibase
  liquibase:
    enabled: true
    change-log: "classpath:db/changelog/db.changelog-master.yaml"
    liquibaseSchema: "hopes"

