---
spring:
  profiles:
    active: prod
  liquibase:
    contexts: prod
  # Data base access configuration
  datasource:
    driver-class-name: org.postgresql.Driver
    url: "jdbc:postgresql://localhost:5432/hopes_back"
    username: postgres
    password: postgres
  data:
    # Mongo
    mongodb:
      database: hopes_back
      host: localhost
      port: 27017
      username: root
      password: root
  # Mail
  mail:
    host: "localhost"
    port: 1025
    username:
    password:
    default-encoding: "UTF-8"
    protocol: smtp
    smtp:
      auth: false
      starttls:
        enable: false
    test-connection: false

# Image gallery
imagegallery:
  url: http://localhost:8081/v1

pros:
  url: http://192.168.110.45:${configuration.port.pro}/v1
