---
plexus:
  hopes:
    email:
      template:
        default-sender: "support-hopes@plexus.services"
        support-sender: "support-hopes@plexus.services"
        reset-password-url: "/user/reset_password?token="
    ldap:
      dn-patterns: "uid={0},ou=people"
      group-search-base: "ou=groups"
      url: "ldap://localhost:8389/dc=springframework,dc=org"
      password-attribute: "userPassword"

# Server settings
server:
  port: 8080
  servlet:
    context-path: "/v1"
  tomcat:
    uri-encoding: UTF-8
spring:
  profiles:
    active: @spring.profiles.active@
  jpa:
    # Hibernate
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
        default_schema: "hopes"
        #enable_lazy_load_no_trans: true
    open-in-view: false
    show-sql: false
  # Thymeleaf
  thymeleaf:
    cache: false
    enabled: true
    prefix: "classpath:/templates/"
    suffix: ".html"
  # Liquibase
  liquibase:
    enabled: true
    change-log: "classpath:db/changelog/db.changelog-master.yaml"
    liquibaseSchema: "hopes"
  # Mail
  mail:
    host: "localhost"
    port: 1025
    username:
    password:
    default-encoding: "UTF-8"
    protocol: smtp
    smtp:
      auth: false
      starttls:
        enable: false
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  messages:
    basename: i18n.messages
  ldap:
    #TEST LDAP
    embedded:
      ldif: classpath:test-server.ldif
      base-dn: dc=springframework,dc=org
      port: 8389

# Logging
logging:
  level:
    root: INFO
    liquibase: INFO
    es:
      plexus:
        hopes: DEBUG

# Image gallery
imagegallery:
  url: http://localhost:8081/v1
  
# Cron Migration
cronexpression:
  diagnosis: 0 0 1 * * ?  # At 01:00:00am every day. 0/30 * * * * ? each 30sg
  treatment: 0 0 4 * * ?   # At 04:00:00am every day. 0/30 * * * * ? each 30sg

