---
# Server settings
server:
  port: ${configuration.port.back}
  servlet:
    context-path: "/v1"
  tomcat:
    uri-encoding: UTF-8

spring:
  profiles:
    active: ${spring.profiles.active}
  liquibase:
    contexts: ${spring.profiles.active}
  # Data base access configuration
  datasource:
    driver-class-name: org.postgresql.Driver
    url: "jdbc:postgresql://192.168.110.45:5432/hopes_back"
    username: postgres
    password: postgres
  data:
    # Mongo
    mongodb:
      database: hopes_back
      host: 192.168.110.45
      port: 27017
      username: root
      password: root
  # Mail
  mail:
    host: "in-v3.mailjet.com"
    port: 587
    username: "cc2db7b964d9c29959b03d5f2dc690f5"
    password: "24d9d686cb16587debf7a316f8a3e033"
    default-encoding: "UTF-8"
    protocol: smtp
    smtp:
      auth: true
      connectiontimeout: 5000
      timeout: 5000
      writetimeout: 5000
      starttls:
        enable: true
    test-connection: true
  ldap:
    #TEST LDAP
    embedded:
      ldif: classpath:test-server.ldif
      base-dn: dc=springframework,dc=org
      port: ${configuration.port.ldap}
# Image gallery
imagegallery:
  url: http://192.168.110.45:${configuration.port.back-image}/v1
