---
# Server settings
server:
  port: 8080
  servlet:
    context-path: "/v1"
  tomcat:
    uri-encoding: UTF-8

spring:
  profiles:
    active: ${spring.profiles.active}
  liquibase:
    contexts: ${spring.profiles.active}
  # Data base access configuration
  datasource:
    driver-class-name: org.postgresql.Driver
    url: "jdbc:postgresql://localhost:5432/hopes_back"
    username: postgres
    password: postgres
  data:
    # Mongo
    mongodb:
      database: hopes_back
      host: localhost
      port: 27017
      username: root
      password: root
  # Mail
  mail:
    host: "localhost"
    port: 587
    username: "support-hopes@plexus.services"
    password: "2B4yrH3s9i9ZE"
    default-encoding: "UTF-8"
    protocol: smtp
    smtp:
      auth: true
      connectiontimeout: 5000
      timeout: 5000
      writetimeout: 5000
      starttls:
        enable: true
    test-connection: true
  ldap:
    #TEST LDAP
    embedded:
      ldif: classpath:test-server.ldif
      base-dn: dc=springframework,dc=org
      port: 8389
# Image gallery
imagegallery:
  url: http://localhost:8081/v1
