---
spring:
  profiles:
    active: pre
  liquibase:
    contexts: dev
  # Data base access configuration
  datasource:
    driver-class-name: org.postgresql.Driver
    url: "jdbc:postgresql://192.168.110.45:5432/hopes_back"
    username: postgres
    password: postgres
  data:
    # Mongo
    mongodb:
      database: hopes_back
      host: 192.168.110.45
      port: 27017
      username: root
      password: root
  # Mail
  mail:
    host: "mail.tecnologiasplexus.com"
    port: 587
    username: "support-hopes@plexus.services"
    password: "2B4yrH3s9i9ZE"
    default-encoding: "UTF-8"
    protocol: smtp
    smtp:
      auth: true
      connectiontimeout: 5000
      timeout: 5000
      writetimeout: 5000
      starttls:
        enable: true
    test-connection: true

# Image gallery
imagegallery:
  url: http://192.168.110.45:8081/v1
